### ISSUE TITLE
[需修正] N + 1 問題，大量爆發中！

### ISSUE THREAD

**Issue by vito588p** [astrocamp/14th-JoBand#253]
先前專案時，因為時間緊迫，其實我們都忘了注意。

剛好我為了實作新套件，一放進去就狂跳通知，哈哈哈

如以下：

**Comment by vito588p** [comment]
VM19:5 user: weber
USE eager loading detected
  Profile => [:avatar_attachment]
  Add to your query: .includes([:avatar_attachment])
Call stack
  /Users/weber/Documents/Dev_Project/Joband/app/views/shared/_avatar.html.erb:1:in `_app_views_shared__avatar_html_erb___4541314200839303378_37220'
  /Users/weber/Documents/Dev_Project/Joband/app/views/profiles/_profile.html.erb:5:in `block in _app_views_profiles__profile_html_erb__443212174389703690_38420'
  /Users/weber/Documents/Dev_Project/Joband/app/views/profiles/_profile.html.erb:1:in `_app_views_profiles__profile_html_erb__443212174389703690_38420'
  /Users/weber/Documents/Dev_Project/Joband/app/views/profiles/index.html.erb:32:in `_app_views_profiles_index_html_erb___2618835407070898196_38340'
  /Users/weber/Documents/Dev_Project/Joband/app/controllers/application_controller.rb:21:in `switch_locale'

**Comment by vito588p** [comment]
user: weber
USE eager loading detected
  Post => [:user]
  Add to your query: .includes([:user])
Call stack
  /Users/weber/Documents/Dev_Project/Joband/app/views/posts/_posts.html.erb:4:in `_app_views_posts__posts_html_erb___2022405280853133800_39880'
  /Users/weber/Documents/Dev_Project/Joband/app/views/posts/index.html.erb:57:in `block (2 levels) in _app_views_posts_index_html_erb___744781023891093761_39560'
  /Users/weber/Documents/Dev_Project/Joband/app/views/posts/index.html.erb:56:in `block in _app_views_posts_index_html_erb___744781023891093761_39560'
  /Users/weber/Documents/Dev_Project/Joband/app/views/posts/index.html.erb:52:in `_app_views_posts_index_html_erb___744781023891093761_39560'
  /Users/weber/Documents/Dev_Project/Joband/app/controllers/application_controller.rb:21:in `switch_locale'

**Comment by vito588p** [comment]
user: weber
USE eager loading detected
  Post => [:comments]
  Add to your query: .includes([:comments])
Call stack
  /Users/weber/Documents/Dev_Project/Joband/app/views/posts/_controls.html.erb:15:in `_app_views_posts__controls_html_erb___4273886128459310820_39900'
  /Users/weber/Documents/Dev_Project/Joband/app/views/posts/_posts.html.erb:10:in `_app_views_posts__posts_html_erb___2022405280853133800_39880'
  /Users/weber/Documents/Dev_Project/Joband/app/views/posts/index.html.erb:57:in `block (2 levels) in _app_views_posts_index_html_erb___744781023891093761_39560'
  /Users/weber/Documents/Dev_Project/Joband/app/views/posts/index.html.erb:56:in `block in _app_views_posts_index_html_erb___744781023891093761_39560'
  /Users/weber/Documents/Dev_Project/Joband/app/views/posts/index.html.erb:52:in `_app_views_posts_index_html_erb___744781023891093761_39560'
  /Users/weber/Documents/Dev_Project/Joband/app/controllers/application_controller.rb:21:in `switch_locale'

**Comment by vito588p** [comment]
user: weber
AVOID eager loading detected
  Post => [:like_logs]
  Remove from your query: .includes([:like_logs])
Call stack
  /Users/weber/Documents/Dev_Project/Joband/app/views/comments/_comment_post.html.erb:3:in `_app_views_comments__comment_post_html_erb___2940855066607460913_39940'
  /Users/weber/Documents/Dev_Project/Joband/app/views/posts/_posts.html.erb:21:in `_app_views_posts__posts_html_erb___2022405280853133800_39880'
  /Users/weber/Documents/Dev_Project/Joband/app/views/posts/index.html.erb:57:in `block (2 levels) in _app_views_posts_index_html_erb___744781023891093761_39560'
  /Users/weber/Documents/Dev_Project/Joband/app/views/posts/index.html.erb:56:in `block in _app_views_posts_index_html_erb___744781023891093761_39560'
  /Users/weber/Documents/Dev_Project/Joband/app/views/posts/index.html.erb:52:in `_app_views_posts_index_html_erb___744781023891093761_39560'
  /Users/weber/Documents/Dev_Project/Joband/app/controllers/application_controller.rb:21:in `switch_locale'

**Comment by vito588p** [comment]
user: weber
USE eager loading detected
  Band => [:avatar_attachment]
  Add to your query: .includes([:avatar_attachment])
Call stack
  /Users/weber/Documents/Dev_Project/Joband/app/views/shared/_avatar.html.erb:1:in `_app_views_shared__avatar_html_erb___4541314200839303378_37220'
  /Users/weber/Documents/Dev_Project/Joband/app/views/bands/_band.html.erb:6:in `block in _app_views_bands__band_html_erb__3206246612092541857_38960'
  /Users/weber/Documents/Dev_Project/Joband/app/views/bands/_band.html.erb:1:in `_app_views_bands__band_html_erb__3206246612092541857_38960'
  /Users/weber/Documents/Dev_Project/Joband/app/views/bands/index.html.erb:32:in `_app_views_bands_index_html_erb___2786540085714222511_38900'
  /Users/weber/Documents/Dev_Project/Joband/app/controllers/application_controller.rb:21:in `switch_locale'

**Comment by vito588p** [comment]
user: weber
USE eager loading detected
  Band => [:rich_text_content]
  Add to your query: .includes([:rich_text_content])
Call stack
  /Users/weber/Documents/Dev_Project/Joband/app/views/bands/_band.html.erb:15:in `block in _app_views_bands__band_html_erb__3206246612092541857_38960'
  /Users/weber/Documents/Dev_Project/Joband/app/views/bands/_band.html.erb:1:in `_app_views_bands__band_html_erb__3206246612092541857_38960'
  /Users/weber/Documents/Dev_Project/Joband/app/views/bands/index.html.erb:32:in `_app_views_bands_index_html_erb___2786540085714222511_38900'
  /Users/weber/Documents/Dev_Project/Joband/app/controllers/application_controller.rb:21:in `switch_locale'

**Comment by vito588p** [comment]
VM282:5 user: weber
USE eager loading detected
  Activity => [:banner_attachment]
  Add to your query: .includes([:banner_attachment])
Call stack
  /Users/weber/Documents/Dev_Project/Joband/app/views/shared/_activityBanner.html.erb:1:in `_app_views_shared__activity_anner_html_erb__170817788323782028_42360'
  /Users/weber/Documents/Dev_Project/Joband/app/views/activities/_activity.html.erb:5:in `block in _app_views_activities__activity_html_erb___180071216172263213_42340'
  /Users/weber/Documents/Dev_Project/Joband/app/views/activities/_activity.html.erb:1:in `_app_views_activities__activity_html_erb___180071216172263213_42340'
  /Users/weber/Documents/Dev_Project/Joband/app/views/activities/activity_index.html.erb:19:in `_app_views_activities_activity_index_html_erb__2717388824248520852_39440'
  /Users/weber/Documents/Dev_Project/Joband/app/controllers/application_controller.rb:21:in `switch_locale'

**Comment by vito588p** [comment]
user: weber
USE eager loading detected
  Activity => [:band]
  Add to your query: .includes([:band])
Call stack
  /Users/weber/Documents/Dev_Project/Joband/app/views/activities/_activity.html.erb:31:in `block in _app_views_activities__activity_html_erb___180071216172263213_42340'
  /Users/weber/Documents/Dev_Project/Joband/app/views/activities/_activity.html.erb:1:in `_app_views_activities__activity_html_erb___180071216172263213_42340'
  /Users/weber/Documents/Dev_Project/Joband/app/views/activities/activity_index.html.erb:19:in `_app_views_activities_activity_index_html_erb__2717388824248520852_39440'
  /Users/weber/Documents/Dev_Project/Joband/app/controllers/application_controller.rb:21:in `switch_locale'

**Comment by andy840818** [comment]
怎麼修 XDD includes 要放在哪

**Comment by LeoChang0808** [comment]
剛好最近也疑似遇到這問題ＸＤ
https://hackmd.io/@were1122was/BkUpHXuAq

includes 放 controller 的樣子
